version: '3.8'

services:
  front-web:
    build:
      context: .
      dockerfile: deploy/Dockerfile
      args:
        - BACKEND_URL=${BACKEND_URL:-http://localhost:8082}
        - BACKEND_AUTH_URL=${BACKEND_AUTH_URL:-http://localhost:8081}
        - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-WkT7w36shWPBmOOSEOGPt}
    container_name: front-web-integrado
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8082}
      - BACKEND_AUTH_URL=${BACKEND_AUTH_URL:-http://localhost:8081}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-WkT7w36shWPBmOOSEOGPt}
      - PORT=3000
    volumes:
      - ./logs:/app/logs
    networks:
      - ms-net
    restart: "no"

networks:
  ms-net:
    external: true
